-- Badal Deposit -> 888STARZ -> CashdeskBot Payout -> Badal Wallet.
--
-- The customer redeems a one-time withdrawal code that 888STARZ generated
-- on its side; CashdeskBot's /Deposit/{userId}/Payout confirms and reports
-- the amount. Every redemption attempt (success or failure) is logged here
-- for support/dispute audit and, more importantly, to make sure the same
-- code can never credit the wallet twice from our side -- the unique index
-- below rejects a second row for a code that already succeeded once.
CREATE TABLE cashdeskbot_payouts (
  id                      UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  customer_id             UUID NOT NULL REFERENCES users(id),
  winwin_id               TEXT NOT NULL, -- 888STARZ Player ID
  code                    TEXT NOT NULL, -- 4-digit withdrawal code generated by 888STARZ
  success                 BOOLEAN NOT NULL,
  amount_cents            BIGINT,        -- CashdeskBot's confirmed `summa`, only set on success
  cashdeskbot_message_id  TEXT,          -- CashdeskBot's `messageId`, for reference/dispute lookup
  message                 TEXT,          -- CashdeskBot's own response message, admin-facing only
  order_id                UUID REFERENCES orders(id),
  created_at              TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE UNIQUE INDEX idx_cashdeskbot_payouts_redeemed_code ON cashdeskbot_payouts(winwin_id, code) WHERE success = true;
CREATE INDEX idx_cashdeskbot_payouts_customer ON cashdeskbot_payouts(customer_id, created_at DESC);
